// <auto-generated />
namespace lzz博客.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class flink2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flink2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701190202298_flink2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
